### ISSUE TITLE
Upgrade to ZF3

### ISSUE THREAD

**Issue by cbleek** [cross-solution/YAWIK#335]
Support for ZF2 will be dropped.

After an Upgrade to ZF3  #317 and #318 can propably closed.  

Migration Path is described at https://docs.zendframework.com/zend-servicemanager/migration/

- [x] [FactoryInterface](https://github.com/cross-solution/YAWIK/issues/336). All Factories must implement the __invoke()
- [x] [AbstractFactoryInterface](https://github.com/cross-solution/YAWIK/issues/338)
- [x] [SharedListenerAggregateInterface](https://github.com/cross-solution/YAWIK/issues/337)
- [x] fix Unittest in do-not-added-attributes-directly #348
- [x] fix the mvctranslater problem #351
- [x] Call to undefined function Auth\Listener\AuthAggregateListener::factory()
----

- [x] [Namespace change](https://github.com/cross-solution/YAWIK/issues/339)
- [x] [Code Cleanups after Composer Upgrade](https://github.com/cross-solution/YAWIK/issues/340)

**Comment by cbleek** [comment]
hi @kilip , I've just commited a modification on a factory.
https://github.com/cross-solution/YAWIK/commit/31fe0204990089afb39478de57d9e258df533c08
